name: Premier Test GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  premier-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: 2. Exécuter une commande de test
        run: |
          echo "🎉 Bravo ! Le workflow GitHub Actions a été déclenché avec succès."
          echo "📂 Liste des fichiers récupérés sur le serveur GitHub :"
          ls -la